name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools
    
    - name: Install pipx
      run: |
        python -m pip install --upgrade pipx
    
    - name: Install Poetry using pipx
      run: |
        pipx install poetry
    
    - name: Configure Poetry
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    
    - name: Install dependencies
      run: poetry install --no-dev
    
    - name: Run tests
      run: poetry run pytest
    
    - name: Build and publish
      run: |
        set -e
        poetry build
        poetry publish
